"""
Training data for spaCy text categorizer.
Each entry is (description, {cats: {category: score}}).
Score of 1.0 = this IS the category, 0.0 = this is NOT the category.
"""

CATEGORIES = ['food', 'transport', 'utilities', 'entertainment', 'health', 'shopping', 'income', 'savings', 'other']

def make_cats(positive_cat):
    """Helper: creates a cats dict with 1.0 for the positive category, 0.0 for all others."""
    return {cat: 1.0 if cat == positive_cat else 0.0 for cat in CATEGORIES}

TRAIN_DATA = [
    # === FOOD ===
    ("SHOPRITE ACCRA MALL POS PURCHASE", make_cats("food")),
    ("KFC OSTAMEL BRANCH POS", make_cats("food")),
    ("PIZZA INN DELIVERY ORDER", make_cats("food")),
    ("RESTAURANT PAYMENT OKAISHIE", make_cats("food")),
    ("CHOP BAR MADINA PURCHASE", make_cats("food")),
    ("PAPAYE FAST FOOD OKAISHIE", make_cats("food")),
    ("CHICKEN INN KANESHIE", make_cats("food")),
    ("GROCERY STORE EAST LEGON", make_cats("food")),
    ("MELCOM FOOD SECTION PURCHASE", make_cats("food")),
    ("BAKERY PURCHASE LABONE", make_cats("food")),
    ("CAFE LATTE COFFEE SHOP OSU", make_cats("food")),
    ("CANTEEN LUNCH PAYMENT", make_cats("food")),
    ("SUPERMARKET GROCERIES TEMA", make_cats("food")),
    ("FOOD DELIVERY BOLT FOOD", make_cats("food")),
    ("BURGER KING ACCRA MALL", make_cats("food")),
    ("STREET FOOD VENDOR CIRCLE", make_cats("food")),
    ("EATERY PAYMENT DANSOMAN", make_cats("food")),
    ("KOFI BROKEMAN GROUNDNUT PURCHASE", make_cats("food")),
    ("MARKET WOMAN MAKOLA FOODSTUFFS", make_cats("food")),
    ("FRESH FISH PURCHASE TEMA HARBOUR", make_cats("food")),

    # === TRANSPORT ===
    ("UBER TRIP ACCRA", make_cats("transport")),
    ("BOLT RIDE EAST LEGON TO AIRPORT", make_cats("transport")),
    ("TROTRO FARE MADINA TO CIRCLE", make_cats("transport")),
    ("GOIL FILLING STATION FUEL", make_cats("transport")),
    ("TOTAL PETROL PURCHASE", make_cats("transport")),
    ("SHELL FUEL STATION TEMA", make_cats("transport")),
    ("TAXI FARE AIRPORT", make_cats("transport")),
    ("BUS TICKET KUMASI VIP", make_cats("transport")),
    ("PARKING FEE ACCRA MALL", make_cats("transport")),
    ("TOLL BOOTH TEMA MOTORWAY", make_cats("transport")),
    ("CAR WASH EAST LEGON", make_cats("transport")),
    ("UBER EATS DELIVERY FEE", make_cats("transport")),
    ("INDRIVER TRIP KASOA", make_cats("transport")),
    ("OLA CAB RIDE CIRCLE", make_cats("transport")),
    ("FUEL PURCHASE PUMA STATION", make_cats("transport")),
    ("STC BUS TICKET ACCRA KUMASI", make_cats("transport")),
    ("CAR MAINTENANCE ABOSSEY OKAI", make_cats("transport")),
    ("TYRE REPAIR KANESHIE", make_cats("transport")),
    ("VEHICLE INSURANCE RENEWAL", make_cats("transport")),
    ("DVLA LICENSE RENEWAL", make_cats("transport")),

    # === UTILITIES ===
    ("ECG PREPAID PURCHASE", make_cats("utilities")),
    ("GHANA WATER COMPANY BILL", make_cats("utilities")),
    ("MTN BILL PAYMENT AIRTIME", make_cats("utilities")),
    ("VODAFONE BROADBAND PAYMENT", make_cats("utilities")),
    ("AIRTEL TIGO RECHARGE", make_cats("utilities")),
    ("DSTV SUBSCRIPTION PAYMENT", make_cats("utilities")),
    ("STARTIMES MONTHLY BILL", make_cats("utilities")),
    ("GOTV SUBSCRIPTION RENEWAL", make_cats("utilities")),
    ("ELECTRICITY BILL PAYMENT KUMASI", make_cats("utilities")),
    ("WATER BILL TEMA METROPOLITAN", make_cats("utilities")),
    ("INTERNET SERVICE PROVIDER PAYMENT", make_cats("utilities")),
    ("WIFI SUBSCRIPTION SURFLINE", make_cats("utilities")),
    ("PREPAID METER RECHARGE", make_cats("utilities")),
    ("MTN FIBER BROADBAND", make_cats("utilities")),
    ("TELECEL DATA BUNDLE", make_cats("utilities")),
    ("CABLE TV MONTHLY CHARGE", make_cats("utilities")),
    ("POSTPAID ELECTRICITY ECG", make_cats("utilities")),
    ("MTN DATA BUNDLE 5GB", make_cats("utilities")),
    ("VODAFONE MONTHLY PLAN", make_cats("utilities")),
    ("HOME INTERNET RENEWAL", make_cats("utilities")),

    # === ENTERTAINMENT ===
    ("NETFLIX MONTHLY SUBSCRIPTION", make_cats("entertainment")),
    ("SILVERBIRD CINEMA TICKET", make_cats("entertainment")),
    ("SPOTIFY PREMIUM PAYMENT", make_cats("entertainment")),
    ("YOUTUBE PREMIUM SUB", make_cats("entertainment")),
    ("SHOWMAX SUBSCRIPTION", make_cats("entertainment")),
    ("CLUB ENTRANCE FEE OYSTERBAY", make_cats("entertainment")),
    ("BAR TAB PAYMENT OSU", make_cats("entertainment")),
    ("LOUNGE DRINKS LABONE", make_cats("entertainment")),
    ("GAME CENTER ACCRA MALL", make_cats("entertainment")),
    ("BETTING STAKE SPORTYBET", make_cats("entertainment")),
    ("APPLE MUSIC SUBSCRIPTION", make_cats("entertainment")),
    ("CONCERT TICKET PURCHASE", make_cats("entertainment")),
    ("MOVIE TICKET WEST HILLS MALL", make_cats("entertainment")),
    ("BOWLING ALLEY ACCRA", make_cats("entertainment")),
    ("BEACH RESORT DAY PASS", make_cats("entertainment")),
    ("POOL PARTY ENTRANCE", make_cats("entertainment")),
    ("KARAOKE NIGHT PAYMENT", make_cats("entertainment")),
    ("DISNEY PLUS SUBSCRIPTION", make_cats("entertainment")),
    ("TIKTOK COINS PURCHASE", make_cats("entertainment")),
    ("AMAZON PRIME VIDEO", make_cats("entertainment")),

    # === HEALTH ===
    ("PHARMACY PURCHASE EAST LEGON", make_cats("health")),
    ("KORLE BU HOSPITAL PAYMENT", make_cats("health")),
    ("MEDICAL LAB TEST FEE", make_cats("health")),
    ("DOCTOR CONSULTATION FEE", make_cats("health")),
    ("DENTAL CLINIC PAYMENT", make_cats("health")),
    ("OPTICIAN EYE TEST", make_cats("health")),
    ("DRUG STORE PURCHASE MADINA", make_cats("health")),
    ("NHIS REGISTRATION FEE", make_cats("health")),
    ("CLINIC VISIT SPINTEX", make_cats("health")),
    ("HOSPITAL BILL PAYMENT 37 MILITARY", make_cats("health")),
    ("PHYSIOTHERAPY SESSION", make_cats("health")),
    ("HEALTH INSURANCE PREMIUM", make_cats("health")),
    ("BLOOD TEST LAB FEE", make_cats("health")),
    ("PRESCRIPTION DRUGS PURCHASE", make_cats("health")),
    ("AMBULANCE SERVICE FEE", make_cats("health")),
    ("MATERNITY WARD PAYMENT", make_cats("health")),
    ("X-RAY SCAN RIDGE HOSPITAL", make_cats("health")),
    ("MENTAL HEALTH COUNSELING", make_cats("health")),
    ("VACCINE PAYMENT", make_cats("health")),
    ("DENTAL BRACES INSTALLMENT", make_cats("health")),

    # === SHOPPING ===
    ("MELCOM SHOPPING ACCRA", make_cats("shopping")),
    ("JUMIA ONLINE ORDER", make_cats("shopping")),
    ("ACCRA MALL CLOTHING STORE", make_cats("shopping")),
    ("ELECTRONICS SHOP CIRCLE", make_cats("shopping")),
    ("MAKOLA MARKET PURCHASE", make_cats("shopping")),
    ("PALACE MALL KUMASI", make_cats("shopping")),
    ("WEST HILLS MALL PURCHASE", make_cats("shopping")),
    ("AMAZON ONLINE ORDER", make_cats("shopping")),
    ("ZARA CLOTHING PURCHASE", make_cats("shopping")),
    ("NIKE STORE ACCRA MALL", make_cats("shopping")),
    ("COMPUTER VILLAGE PURCHASE", make_cats("shopping")),
    ("PHONE ACCESSORIES KANTAMANTO", make_cats("shopping")),
    ("FURNITURE STORE PURCHASE", make_cats("shopping")),
    ("HOME DECOR EAST LEGON", make_cats("shopping")),
    ("BOOKSHOP EPP PURCHASE", make_cats("shopping")),
    ("ALIEXPRESS ORDER PAYMENT", make_cats("shopping")),
    ("SHEIN ORDER DELIVERY", make_cats("shopping")),
    ("COSMETICS STORE OSU", make_cats("shopping")),
    ("HARDWARE STORE ABOSSEY OKAI", make_cats("shopping")),
    ("GIFT SHOP PURCHASE LABADI", make_cats("shopping")),

    # === INCOME ===
    ("SALARY PAYMENT FROM EMPLOYER", make_cats("income")),
    ("PAYROLL CREDIT COMPANY LTD", make_cats("income")),
    ("TRANSFER IN FROM SAVINGS", make_cats("income")),
    ("CREDIT ALERT RECEIVED", make_cats("income")),
    ("MOMO RECEIVED FROM FRIEND", make_cats("income")),
    ("PAYMENT RECEIVED FOR SERVICES", make_cats("income")),
    ("DEPOSIT CASH AT BRANCH", make_cats("income")),
    ("EMPLOYER WAGE PAYMENT", make_cats("income")),
    ("FREELANCE PAYMENT RECEIVED", make_cats("income")),
    ("REFUND CREDIT TO ACCOUNT", make_cats("income")),
    ("DIVIDEND PAYMENT RECEIVED", make_cats("income")),
    ("SCHOLARSHIP DISBURSEMENT", make_cats("income")),
    ("GRANT PAYMENT RECEIVED", make_cats("income")),
    ("COMMISSION PAYMENT", make_cats("income")),
    ("BONUS SALARY CREDIT", make_cats("income")),
    ("CASH DEPOSIT ATM", make_cats("income")),
    ("INTERBANK TRANSFER RECEIVED", make_cats("income")),
    ("RENTAL INCOME PAYMENT", make_cats("income")),
    ("GIFT MONEY RECEIVED", make_cats("income")),
    ("NSSFUND WITHDRAWAL CREDIT", make_cats("income")),

    # === SAVINGS ===
    ("BANK TRANSFER TO SAVINGS", make_cats("savings")),
    ("MOBILE MONEY SEND TO FRIEND", make_cats("savings")),
    ("SAVINGS DEPOSIT MONTHLY", make_cats("savings")),
    ("MOMO TRANSFER TO MERCHANT", make_cats("savings")),
    ("VISA CARD TOP UP DMRWZZUZ", make_cats("savings")),
    ("STANDING ORDER SAVINGS ACCOUNT", make_cats("savings")),
    ("TRANSFER TO FIXED DEPOSIT", make_cats("savings")),
    ("MTN MOMO CASH OUT", make_cats("savings")),
    ("SEND MONEY TO FAMILY", make_cats("savings")),
    ("INVESTMENT ACCOUNT DEPOSIT", make_cats("savings")),
    ("SUSU COLLECTOR PAYMENT", make_cats("savings")),
    ("PENSION FUND CONTRIBUTION", make_cats("savings")),
    ("MUTUAL FUND PURCHASE", make_cats("savings")),
    ("TREASURY BILL PURCHASE", make_cats("savings")),
    ("WIRE TRANSFER OUTGOING", make_cats("savings")),
    ("REMITTANCE SEND ABROAD", make_cats("savings")),
    ("INTERBANK TRANSFER SENT", make_cats("savings")),
    ("MOBILE MONEY WITHDRAWAL", make_cats("savings")),
    ("ATM WITHDRAWAL CASH", make_cats("savings")),
    ("BANK DRAFT PURCHASE", make_cats("savings")),

    # === OTHER ===
    ("300304******0000 00000001 REF 073604985008", make_cats("other")),
    ("UNKNOWN TRANSACTION REFERENCE", make_cats("other")),
    ("MISC CHARGE ACCOUNT FEE", make_cats("other")),
    ("BANK CHARGE MONTHLY FEE", make_cats("other")),
    ("ATM MAINTENANCE FEE", make_cats("other")),
    ("SMS ALERT CHARGE", make_cats("other")),
    ("ACCOUNT MAINTENANCE CHARGE", make_cats("other")),
    ("STAMP DUTY PAYMENT", make_cats("other")),
    ("GOVERNMENT TAX DEDUCTION", make_cats("other")),
    ("UNIDENTIFIED DEPOSIT REF", make_cats("other")),
]